service: default
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 1000 --workers 8

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 6
  memory_gb: 30
  disk_size_gb: 50

env_variables:
    # The app will look for the model file at: gs://MODEL_BUCKET/MODEL_FILENAME
    MODEL_BUCKET: blm
    MODEL_FILENAME: qnrf_scale_4_epoch_46_weights.pth